spring:
  application:
    name: hello-client

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  https://eureka-micro.herokuapp.com/eureka/
  instance:
    hostname: eureka-client-micro.herokuapp.com
    
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000  