spring:
  application:
    name: hello-client

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  https://eureka-e668d397-a9ac-475e-8b76-fbe21e0138e9.cfapps.io
  instance:
    hostname: eureka-e668d397-a9ac-475e-8b76-fbe21e0138e9.cfapps.io
    
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000  
